### ISSUE TITLE
several "not found" errors

### ISSUE THREAD

**Issue by KCGD** [uzh-rpg/rpg_timelens#12]
I saw the paper on this AI and was really impressed but the google colab is broken. Several things that it needs to download simply aren't available.

http://rpg.ifi.uzh.ch/timelens/data/checkpoint.bin returns 404
http://rpg.ifi.uzh.ch/timelens/data/example_github.zip also returns 404

**Comment by Acentrage** [comment]
Hi, the data paths were changed in this commit but only for the README.md and not in the Jupyter Notebook: https://github.com/uzh-rpg/rpg_timelens/commit/db720fca71cf702682953782e1d46d761f8d7e8d

The correct paths would be:
http://rpg.ifi.uzh.ch/timelens/data2/checkpoint.bin
http://rpg.ifi.uzh.ch/timelens/data2/example_github.zip

**Comment by johnowhitaker** [comment]
Thank you for providing the correct link - I was just about to give up :)

**Comment by danielgehrig18** [comment]
Hi all, thanks for pointing this out. There was a recent change in the paths and thus the colab broke. They should be fixed now.
