### ISSUE TITLE
How am I supposed to make my own input_events and frames?

### ISSUE THREAD

**Issue by crumbface909** [uzh-rpg/rpg_timelens#16]
I'm trying to try my own video in the colab but it needs a timestamp.txt and input_events and I don't know how to make those.

**Comment by danielgehrig18** [comment]
Hi, this work requires events from an event camera and thus does not work with only video. See #2 
However, if you want to convert your video to synthetic events to play around you can visit this repo: https://github.com/uzh-rpg/rpg_vid2e
