### ISSUE TITLE
Testing with custom RGB data

### ISSUE THREAD

**Issue by n00mkrad** [uzh-rpg/rpg_timelens#2]
Hello, is it possible to use custom frames as input?

How are the npz files generated? Or are they not required for inference?

**Comment by danielgehrig18** [comment]
These files contain events from an event camera and are needed to generate the interpolations.

**Comment by danielgehrig18** [comment]
Check out our [google colab](TimeLens.ipynb) for this .

**Comment by 98mxr** [comment]
The paper contains tests from the vimeo-90K dataset. And introduced that the .npz were generated through another work of them.
from
[https://github.com/uzh-rpg/rpg_vid2e](url)
The project does not seem to be able to directly output .npz files, I am working hard on this work.
English is not my native language. If there are any errors or improper descriptions, I apologize.

**Comment by Zer0xPoint** [comment]
> The paper contains tests from the vimeo-90K dataset. And introduced that the .npz were generated through another work of them.
> from
> [https://github.com/uzh-rpg/rpg_vid2e](url)
> The project does not seem to be able to directly output .npz files, I am working hard on this work.
> English is not my native language. If there are any errors or improper descriptions, I apologize.

any progress?

**Comment by 98mxr** [comment]
> > 该论文包含来自 vimeo-90K 数据集的测试。并介绍了.npz 是通过他们的另一项工作生成的。
> > 来自
> > [https://github.com/uzh-rpg/rpg_vid2e](url)
> > 项目好像不能直接输出.npz文件，我正在努力做这个工作。
> > 英语不是我的母语。如果有任何错误或不恰当的描述，我深表歉意。
> 
> 任何进展？

I tried it, but I lack relevant work experience.
It did not generate as I thought, and now the work is in a stagnant stage.
