### ISSUE TITLE
Model is not downloading correctly

### ISSUE THREAD

**Issue by mathemusician** [uzh-rpg/rpg_timelens#23]
# Description of Problem ❗️

I get a 403 message when I try to access the model
```python
>>> !wget http://rpg.ifi.uzh.ch/timelens/data2/checkpoint.bin
HTTP request sent, awaiting response... 403 Forbidden
```

<br>

# Expected Behavior ✅
model downloads from the web

<br>

# Environment 🛠
Google Colab

<br>

# Additional Comments 🌳
I was using the [Google Colab notebook](https://colab.research.google.com/drive/1wBLoIZB1JynLgl3aw0u7FM6RSTeS0vwf#scrollTo=qSmCBWoy1l_E&line=1&uniqifier=1) included in the repository, but I was not able to download the model. I'm apparently forbidden from downloading or accessing it.

**Comment by danielgehrig18** [comment]
Hi, the link has been updated: you can download the models from here:  http://download.ifi.uzh.ch/rpg/web/data/timelens/data2/example_github.zip
http://download.ifi.uzh.ch/rpg/web/data/timelens/data2/checkpoint.bin

**Comment by mathemusician** [comment]
Thank you! I am working on pruning your model for fast implementation; I'll share with you once I get things up and running!

**Comment by zzzbzzz** [comment]
Hi, the links seem to be invalid now. Could any of you share the links to models and data again? Thanks in advance.

> Hi, the link has been updated: you can download the models from here: http://download.ifi.uzh.ch/rpg/web/data/timelens/data2/example_github.zip http://download.ifi.uzh.ch/rpg/web/data/timelens/data2/checkpoint.bin

**Comment by danielgehrig18** [comment]
Unfortunately, we had some issues with the server, which should have been
resolved by now. Let me know if the problem persists.

**Comment by Ningreka** [comment]
The links seem to be unfortunately invalid again. QAQ
